package za.co.sfy.lucid.sams.resource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import za.co.sfy.lucid.sams.domain.exception.LucidSamsExecutionException;
import za.co.sfy.lucid.sams.resource.connection.DatabaseConnectionManager;
import za.co.sfy.sams.GeneralInfo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

@Component
public class GeneralInfoResource {

    private final DatabaseConnectionManager databaseConnectionManager;

    @Autowired
    public GeneralInfoResource(final DatabaseConnectionManager databaseConnectionManager) {
        this.databaseConnectionManager = databaseConnectionManager;
    }

    public void save(GeneralInfo generalInfo) throws LucidSamsExecutionException {

        Connection databaseConnection = databaseConnectionManager.createDatabaseConnection();

        Statement statement = null;
        try {
            statement = databaseConnection.createStatement();
            String valuesString = buildValuesString(generalInfo);

            statement.executeQuery("INSERT INTO General_Info VALUES (" + valuesString + ")");
            ResultSet resultSet = statement.getResultSet();
            //TODO: row column count mismatch
        } catch (SQLException e) {
            throw new LucidSamsExecutionException("Unable to save to the 'General_Info' table. ", e);
        } finally {
            databaseConnectionManager.closeDatabaseConnection(databaseConnection);
        }
    }

    private String buildValuesString(GeneralInfo generalInfo) {

        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getSchoolID());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getSchoolName());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getProvincialDep());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getDistrict());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getRegion());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getCircuit());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getAddress1());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getAddress2());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getAddress3());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getAddressCode());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPostAddress1());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPostAddress2());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPostAddress3());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTelCode1());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTelephone1());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTelCode2());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTelephone2());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTelcode3());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTelephone3());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getFaxCode());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getFax());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSchool());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTAdd1());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTAdd2());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTAdd3());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTCode());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTtelcode1());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTTel1());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTfaxcode());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTFax());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTPrincipal());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getContactPerson());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getEmisCode());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getEMail());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPredominantLanguage());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPersalPayPoint());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPersalComponent());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getInternetAccess());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getOwnership());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getLandOwnership());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPlatoon());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getHostSchool());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getDoubleShifts());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getExamAuthority());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getExamCentre());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getExamCentreNumber());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getSpecialised());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getSpecialisation());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getFeePeriod());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getFeeMonths());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getMultigrade());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getRemedial());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getSGBStatus());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.isMaintainProperty());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.isExtraMural());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.isTextbooks());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.isServices());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.isAbet());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.isOtherFunctions());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getCensusArea());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getErfNumber());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getEmisHostSchool());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getHostTime());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getExamAuthName());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getCorrespondenceLang());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getNearestTown());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getDistanceTown());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getDistrictCode());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPostalAddressType());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getSchoolLevel());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSSchoolStatus());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSTransactionCategory());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSStatusFlag());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSReportStatusFlag());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSReasonCode());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getLuritsYear());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSSentFileName());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSDateLastUpdate());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSLastUpdatedBy());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getOwnerBuildings());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getLuritsIndicator());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTelcode4());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTelephone4());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getAdminComputers());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPostAddress0());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPostAddress0No());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTEmisCode());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.isUseMarksSecurity());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getPSNP());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getTSIncludesANA());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getLastDBCompact());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getIQMSLastExpDate());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getIQMSLastImpDate());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getExamBoard());
        stringBuilder.append("], ");
        stringBuilder.append("[");
        stringBuilder.append(generalInfo.getExamBoardOther());
//        stringBuilder.append("], ");
//        stringBuilder.append("[");
//        stringBuilder.append("multigradeS");
//        stringBuilder.append("], ");
//        stringBuilder.append("[");
//        stringBuilder.append("EmisOfficer");
//        stringBuilder.append("], ");
//        stringBuilder.append("[");
//        stringBuilder.append("EmisOffEducator");
//        stringBuilder.append("], ");
//        stringBuilder.append("[");
//        stringBuilder.append("EmailAlt");
        stringBuilder.append("]");

        String valuesString = stringBuilder.toString();

        return valuesString;
    }
}